# SELECT CART_ID, MAX(IF(NAME = 'MILK', 1, 0)) AS M, MAX(IF(NAME = 'Yogurt', 1, 0)) AS Y
# FROM CART_PRODUCTS
# WHERE NAME = 'MILK' OR NAME = 'Yogurt'
# GROUP BY CART_ID
# ORDER BY CART_ID

SELECT CART_ID
FROM (
    SELECT CART_ID, MAX(IF(NAME = 'MILK', 1, 0)) AS M, MAX(IF(NAME = 'Yogurt', 1, 0)) AS Y
    FROM CART_PRODUCTS
    WHERE NAME = 'MILK' OR NAME = 'Yogurt'
    GROUP BY CART_ID
    ORDER BY CART_ID
) AS T
WHERE T.M = 1 AND T.Y = 1