-- 코드를 입력하세요
SELECT i.ANIMAL_ID,i.ANIMAL_TYPE,i.NAME
FROM ANIMAL_INS i
LEFT JOIN ANIMAL_OUTS o ON i.ANIMAL_ID = o.ANIMAL_iD
WHERE i.SEX_UPON_INTAKE !=o.SEX_UPON_OUTCOME
AND i.SEX_UPON_INTAKE NOT LIKE 'intact'
ORDER BY i.ANIMAL_ID