SELECT YEAR(o.sales_date) AS YEAR, MONTH(o.sales_date) AS MONTH, i.GENDER AS GENDER, COUNT(DISTINCT o.USER_ID) as USERS
FROM ONLINE_SALE o
LEFT JOIN USER_INFO i
ON o.USER_ID = i.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER