-- 코드를 입력하세요
SELECT p.PRODUCT_ID, p.PRODUCT_NAME, (PRICE * SUM(AMOUNT)) AS TOTAL_SALES
FROM FOOD_PRODUCT p
LEFT JOIN FOOD_ORDER o ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE o.ORDER_ID IS NOT NULL
AND DATE_FORMAT(o.PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC