SELECT
    HISTORY_ID,
    CASE
    	WHEN HISTORY.DURATION_TYPE = '7일 이상' THEN ROUND((100 - DISCOUNT_RATE) / 100 * DAILY_FEE * RENT_DATE, 0)
    	WHEN HISTORY.DURATION_TYPE = '30일 이상' THEN ROUND((100 - DISCOUNT_RATE) / 100 * DAILY_FEE * RENT_DATE, 0)
    	WHEN HISTORY.DURATION_TYPE = '90일 이상' THEN ROUND((100 - DISCOUNT_RATE) / 100 * DAILY_FEE * RENT_DATE, 0)
    	ELSE DAILY_FEE * RENT_DATE
    END AS FEE
FROM (
    SELECT
        HISTORY_ID,
        CAR_ID,
        DATEDIFF(END_DATE, START_DATE) + 1 AS RENT_DATE,
        CASE
            WHEN DATEDIFF(END_DATE, START_DATE) BETWEEN 6 AND 28 THEN '7일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) BETWEEN 29 AND 88 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) >= 89 THEN '90일 이상'
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) AS HISTORY
LEFT JOIN CAR_RENTAL_COMPANY_CAR AS CAR
ON HISTORY.CAR_ID = CAR.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN
ON 
    CAR.CAR_TYPE = PLAN.CAR_TYPE AND
    HISTORY.DURATION_TYPE = PLAN.DURATION_TYPE
WHERE CAR.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC