SELECT T.APNT_NO, p.PT_NAME, p.PT_NO, T.MCDP_CD, T.DR_NAME, T.APNT_YMD
FROM (
    # SELECT PT_NO, MDDR_ID
        SELECT a.APNT_NO, a.PT_NO, a.MCDP_CD, d.DR_NAME, a.APNT_YMD
        FROM APPOINTMENT a 
        LEFT JOIN DOCTOR d on a.MDDR_ID = d.DR_ID
        WHERE a.MCDP_CD = 'CS'
        AND DATE_FORMAT(a.APNT_YMD, '%Y-%m-%d') = '2022-04-13'
        AND a.APNT_CNCL_YN ='N'
) as T
LEFT JOIN PATIENT p
ON T.PT_NO = p.PT_NO
ORDER BY T.APNT_YMD ASC