SELECT 
    p.MEMBER_NAME, 
    r.REVIEW_TEXT, 
    DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE p
JOIN REST_REVIEW r 
ON p.MEMBER_ID = r.MEMBER_ID
# 제일 많은 리뷰수를 가지고 있는 회원의 아이디 추출
WHERE p.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        # 제일 많은 리뷰수
        SELECT COUNT(*) as CNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY CNT DESC
        LIMIT 1
    )
)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC