SELECT b.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR a
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY b
ON a.CAR_ID = b.CAR_ID
WHERE MONTH(b.START_DATE) = 10
AND a.CAR_TYPE = '세단'
GROUP BY b.CAR_ID
ORDER BY b.CAR_ID DESC